openapi: 3.0.3
info:
  title: Product API
  version: 1.0.1
  description: Provide products specification and categories
paths:
  /products:
    get:
      description: Provide a list of products
      operationId: findProducts
      parameters:
        - in: query
          name: productName
          required: false
          schema:
            type: string
        - in: query
          name: productCategory
          required: false
          schema:
            type: string
      responses:
        200:
          description: List of products populated successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      description: Create a new product
      operationId: createProduct
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        201:
          description: Product created successfully
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
